### ISSUE TITLE
On Windows, `yosys-smtbmc` (a Python tool) is saved as an EXE file, rather than as a `.py` file

### ISSUE THREAD

**Issue by The6P4C** [FPGAwars/toolchain-icestorm#72]
On Linux systems, no suffix is added and the shebang line at the start of the file ensures it is executed correctly. However, on Windows, the Python script is given a `.exe` extension and therefore cannot be run without first renaming to a `.py` file.

The offending line is below. `$EXE` is given the value `".exe"` on Windows, and is empty on Linux builds (as set [here](https://github.com/FPGAwars/toolchain-icestorm/blob/master/scripts/build_setup.sh#L35), on lines 28 and 35 of `scripts/build_setup.sh`).

https://github.com/FPGAwars/toolchain-icestorm/blob/master/scripts/compile_yosys.sh#L84

Solution is to either add a `.py` extension to the file on both platforms (a bad approach for Linux) or introduce a new variable to the build script (`$PY`) which is appended instead.

**Comment by The6P4C** [comment]
A similar issue exists with `yosys-config.exe`, which is actually a shell script. This one's obviously a little harder to fix for Windows installs.

**Comment by Jesus89** [comment]
:+1:
